import './HomePage.css'

function HomePage() {
  return (
    <div>
        <div className="fixed-header" id="#">
          <div className="container">
              <nav>
                <a href="javascript:void(0)" style={{fontSize: 'xx-large', fontWeight: '900', color: '#ffffff', marginRight: '50px', marginLeft: '100px'}}>PredictChain</a>
                <a href="javascript:void(0)" style={{marginLeft: '400px'}}>Create Account</a>
                <a href="javascript:void(0)" style={{marginLeft: '150px'}}>Login</a>
                <a href="javascript:void(0)"style={{marginLeft: '150px'}}>FAQ</a>
                <a href="javascript:void(0)" style={{marginLeft: '150px'}}>Meet The Team</a>
                <a href="https://github.com/AI-and-Blockchain/S23_PredictChain" style={{marginLeft: '150px'}}>Docs</a>
              </nav>
          </div>
        </div>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Arcu non sodales neque sodales. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Vitae nunc sed velit dignissim. Ullamcorper dignissim cras tincidunt lobortis feugiat. Massa tincidunt nunc pulvinar sapien et ligula. Tempor orci eu lobortis elementum nibh tellus molestie. Accumsan lacus vel facilisis volutpat. Consequat nisl vel pretium lectus quam id leo in. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Ultrices eros in cursus turpis massa. Risus at ultrices mi tempus imperdiet nulla malesuada.
          Et tortor consequat id porta nibh venenatis. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Amet consectetur adipiscing elit ut aliquam purus sit amet luctus. Vitae suscipit tellus mauris a diam maecenas sed enim. Leo duis ut diam quam nulla. Molestie ac feugiat sed lectus vestibulum mattis. Sed vulputate mi sit amet mauris commodo quis imperdiet massa. Sed odio morbi quis commodo odio aenean sed adipiscing. Cursus in hac habitasse platea dictumst quisque sagittis purus. Odio morbi quis commodo odio aenean sed adipiscing diam. Sed velit dignissim sodales ut eu sem integer vitae.
          Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Eu feugiat pretium nibh ipsum consequat nisl vel. Id aliquet risus feugiat in ante metus dictum. Ut diam quam nulla porttitor massa. Sit amet nulla facilisi morbi tempus. Arcu cursus euismod quis viverra nibh. Nisi vitae suscipit tellus mauris. Lacus luctus accumsan tortor posuere ac ut consequat semper. Morbi tristique senectus et netus et malesuada fames. Netus et malesuada fames ac. Egestas pretium aenean pharetra magna ac placerat. Porttitor leo a diam sollicitudin tempor. Enim neque volutpat ac tincidunt vitae semper. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Posuere sollicitudin aliquam ultrices sagittis. Lacus laoreet non curabitur gravida arcu ac. Feugiat scelerisque varius morbi enim nunc. Amet nulla facilisi morbi tempus iaculis urna. Aenean et tortor at risus viverra adipiscing at in tellus.
          Congue nisi vitae suscipit tellus mauris. Integer malesuada nunc vel risus. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus a. Vitae sapien pellentesque habitant morbi tristique senectus et. Arcu non sodales neque sodales ut. Dolor sed viverra ipsum nunc aliquet bibendum. Justo eget magna fermentum iaculis eu non. Vitae semper quis lectus nulla at volutpat diam ut. Sollicitudin tempor id eu nisl nunc. Lectus quam id leo in. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Nunc sed velit dignissim sodales. Sit amet facilisis magna etiam. Morbi tristique senectus et netus. At erat pellentesque adipiscing commodo elit.
          At urna condimentum mattis pellentesque id nibh. Volutpat lacus laoreet non curabitur gravida arcu. Ac tortor vitae purus faucibus. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Ultrices tincidunt arcu non sodales neque. Fames ac turpis egestas integer eget aliquet. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Pellentesque nec nam aliquam sem et tortor consequat. Viverra vitae congue eu consequat ac felis. Eget egestas purus viverra accumsan. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Purus non enim praesent elementum facilisis leo vel fringilla est. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Quam adipiscing vitae proin sagittis nisl rhoncus mattis. Proin libero nunc consequat interdum. Dui nunc mattis enim ut tellus elementum sagittis vitae.
          Augue neque gravida in fermentum et sollicitudin ac. Rutrum quisque non tellus orci ac auctor augue. Tempus egestas sed sed risus pretium quam vulputate. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Neque vitae tempus quam pellentesque nec nam. Adipiscing enim eu turpis egestas. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Viverra aliquet eget sit amet tellus cras. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus.
          Adipiscing elit pellentesque habitant morbi tristique senectus et. Risus commodo viverra maecenas accumsan lacus. Vivamus at augue eget arcu dictum varius. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Curabitur gravida arcu ac tortor dignissim convallis. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Nisl nunc mi ipsum faucibus vitae aliquet nec. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Bibendum arcu vitae elementum curabitur vitae nunc sed. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Erat velit scelerisque in dictum non consectetur a erat nam. Aliquam faucibus purus in massa tempor nec feugiat. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Urna id volutpat lacus laoreet. In tellus integer feugiat scelerisque varius morbi enim. Id faucibus nisl tincidunt eget nullam non nisi est.
          Tristique magna sit amet purus gravida quis blandit. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Ac felis donec et odio. Suscipit tellus mauris a diam maecenas sed. Volutpat consequat mauris nunc congue. Aliquet nibh praesent tristique magna sit. Odio euismod lacinia at quis risus sed vulputate odio. Morbi leo urna molestie at. Luctus accumsan tortor posuere ac ut consequat semper. Condimentum id venenatis a condimentum vitae sapien. Diam sit amet nisl suscipit adipiscing bibendum est. Est ultricies integer quis auctor elit sed. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Et magnis dis parturient montes nascetur ridiculus. Sollicitudin tempor id eu nisl nunc mi ipsum. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Auctor augue mauris augue neque gravida in fermentum et. In fermentum posuere urna nec. Ut porttitor leo a diam. Arcu risus quis varius quam.
          Etiam non quam lacus suspendisse faucibus. In nulla posuere sollicitudin aliquam. Duis at consectetur lorem donec massa sapien faucibus et molestie. Tristique senectus et netus et malesuada fames ac turpis. Duis at consectetur lorem donec. Ac orci phasellus egestas tellus rutrum. Ultricies integer quis auctor elit sed vulputate. Faucibus turpis in eu mi bibendum neque egestas. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Fringilla phasellus faucibus scelerisque eleifend. Erat velit scelerisque in dictum non consectetur. Fames ac turpis egestas maecenas pharetra convallis. Suspendisse ultrices gravida dictum fusce ut placerat. A lacus vestibulum sed arcu non odio euismod lacinia at. Fermentum leo vel orci porta. Sit amet mauris commodo quis imperdiet. Mollis nunc sed id semper risus in hendrerit. Scelerisque purus semper eget duis at tellus. Tellus mauris a diam maecenas sed enim ut sem.
          Odio eu feugiat pretium nibh ipsum consequat nisl. Tempor id eu nisl nunc mi ipsum. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Sit amet mauris commodo quis imperdiet massa tincidunt. Id velit ut tortor pretium viverra. Vestibulum mattis ullamcorper velit sed ullamcorper. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Faucibus in ornare quam viverra orci sagittis eu. Massa sapien faucibus et molestie ac feugiat sed. Id velit ut tortor pretium. Et odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Diam quis enim lobortis scelerisque. Consectetur libero id faucibus nisl tincidunt eget nullam non nisi.
          Elit pellentesque habitant morbi tristique senectus et. Faucibus a pellentesque sit amet porttitor. Interdum varius sit amet mattis vulputate enim. Interdum velit euismod in pellentesque. Vitae congue eu consequat ac. In massa tempor nec feugiat nisl pretium. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Nisl tincidunt eget nullam non. Eu feugiat pretium nibh ipsum consequat nisl. Urna cursus eget nunc scelerisque viverra mauris. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Quis varius quam quisque id diam vel quam elementum pulvinar.
          Mi bibendum neque egestas congue quisque egestas diam in arcu. Adipiscing elit pellentesque habitant morbi tristique. Id aliquet lectus proin nibh nisl. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Ut tortor pretium viverra suspendisse potenti nullam ac. In nisl nisi scelerisque eu. Quam pellentesque nec nam aliquam sem et. Eu consequat ac felis donec. Semper risus in hendrerit gravida rutrum quisque. In hac habitasse platea dictumst. Feugiat sed lectus vestibulum mattis ullamcorper velit. Ridiculus mus mauris vitae ultricies leo integer. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Pulvinar mattis nunc sed blandit libero volutpat sed. Dignissim convallis aenean et tortor at. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Turpis tincidunt id aliquet risus feugiat.
          Nunc sed id semper risus in hendrerit gravida rutrum. Fermentum et sollicitudin ac orci phasellus. Scelerisque felis imperdiet proin fermentum leo. Ac placerat vestibulum lectus mauris ultrices eros in. Convallis a cras semper auctor. Ornare arcu odio ut sem nulla pharetra. Vitae et leo duis ut diam quam nulla porttitor. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Elit ut aliquam purus sit amet. Dignissim suspendisse in est ante in nibh. Feugiat in ante metus dictum at tempor commodo. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Malesuada fames ac turpis egestas integer. Malesuada fames ac turpis egestas maecenas pharetra.
          Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Quam pellentesque nec nam aliquam. Urna duis convallis convallis tellus id interdum velit. Aliquam ut porttitor leo a diam sollicitudin. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Dignissim sodales ut eu sem integer vitae justo eget magna. Convallis aenean et tortor at risus viverra adipiscing at. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Dignissim sodales ut eu sem integer vitae justo eget magna.
          Sem et tortor consequat id porta nibh venenatis cras. Convallis a cras semper auctor neque vitae. Quis hendrerit dolor magna eget est lorem ipsum. Eget egestas purus viverra accumsan in nisl. Commodo odio aenean sed adipiscing diam. Suspendisse sed nisi lacus sed viverra tellus. Ut sem viverra aliquet eget sit. Tellus pellentesque eu tincidunt tortor aliquam nulla. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Eleifend mi in nulla posuere sollicitudin aliquam. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc.
        </p>
        <div className="fixed-footer">
          <nav>
            <a href="javascript:void(0)" style={{fontSize: 'xx-large', fontWeight: '900', color: '#ffffff', marginRight: '80px', marginLeft: '100px'}}>PredictChain</a>
            <a href="javascript:void(0)" style={{marginLeft: '300px'}}>Create Account</a>
            <a href="javascript:void(0)" style={{marginLeft: '100px'}}>Login</a>
            <a href="javascript:void(0)"style={{marginLeft: '100px'}}>FAQ</a>
            <a href="javascript:void(0)" style={{marginLeft: '100px'}}>Meet The Team</a>
            <a href="https://github.com/AI-and-Blockchain/S23_PredictChain" style={{marginLeft: '100px'}}>Docs</a>
            <a href="#" style={{marginLeft: '100px'}}>Back to top</a>
          </nav>       
        </div>
    </div>
  );
}

export default HomePage;
